"""
Packet protocol for camera mount controller.

Packet format:
  [0xAA][0x55][LEN:u8][MOUNT_ID:u8][SEQ_HI:u8][SEQ_LO:u8][CMD:u8][PAYLOAD...][CRC_HI:u8][CRC_LO:u8]

  LEN  = number of bytes from MOUNT_ID through end of PAYLOAD (does not include CRC).
  CRC  = CRC-16/CCITT-FALSE over bytes from LEN through end of PAYLOAD.

  MOUNT_ID: 0x00 = broadcast all mounts, 0x01-0x05 = individual mounts.
  SEQ:      rolling u16 sequence number; used to match ACK/NACK replies.
"""
from __future__ import annotations

import logging
import struct
from dataclasses import dataclass, field
from enum import IntEnum
from typing import Optional

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

PACKET_START_1 = 0xAA
PACKET_START_2 = 0x55
MOUNT_BROADCAST = 0x00
NUM_MOUNTS = 5
NUM_POSITIONS = 10

# Minimum bytes in a valid packet: start(2) + len(1) + mount_id(1) + seq(2) + cmd(1) + crc(2) = 9
PACKET_MIN_SIZE = 9
PACKET_MAX_PAYLOAD = 256   # raised: CMD_SUBJECT_LIST needs 232 bytes

# Payload sizes for fixed-length large packets
STATE_REPORT_PAYLOAD_LEN = 182   # 10 slots × 16 bytes + 22 bytes metadata
SAVE_SPEEDS_PAYLOAD_LEN  = 72    # (4 PT + 4 SL + 1 ZM) × 8 bytes
NUM_SLOTS = 10

# v2 look-at subject constants
MAX_SUBJECTS           = 8
MAX_SLIDER_MOVES       = 8
SUBJECT_NAME_LEN       = 16
SUBJECT_RECORD_LEN     = 29   # valid(1) + name(16) + x_mm(4f) + y_mm(4f) + z_mm(4f)
SUBJECT_LIST_PAYLOAD_LEN = MAX_SUBJECTS * SUBJECT_RECORD_LEN  # 232


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class Cmd(IntEnum):
    # PC → Mount
    JOG               = 0x01
    GOTO              = 0x02
    SAVE_POS          = 0x03   # legacy alias; use STORE_POS
    SET_SPEED_PRESET  = 0x04
    SET_LIMITS        = 0x05
    FIND_LIMITS       = 0x06
    SET_ORIENTATION   = 0x07
    E_STOP            = 0x08
    GET_STATUS        = 0x09
    PING              = 0x0A
    GET_STATE         = 0x0B   # request full state dump (slots + presets + limits)
    STORE_POS         = 0x0C   # store current position in slot N (1 byte: slot 0-9)
    CLEAR_POS         = 0x0D   # clear slot N (1 byte: slot 0-9)
    SET_ACTIVE_PRESET = 0x0E   # change active preset (2 bytes: group, preset 1-4)
    SAVE_SPEEDS       = 0x0F   # write 9 speed presets to EEPROM (72 bytes)
    GOTO_SLOT         = 0x10   # recall stored position by slot index (2 bytes: slot 0-9, pt_preset 1-4)
    MOVE_REL          = 0x11   # move relative to current position — same payload as GOTO (17 bytes)
    GET_CONFIG        = 0x12   # request speed presets + orientation from mount (no payload)
    FIND_HOME             = 0x13   # home one axis to its min end stop (1 byte: axis)
    SET_STALL_THRESHOLD   = 0x14   # set + persist StallGuard threshold (2 bytes: axis, threshold)

    # PC → Mount  (v2 — look-at tracking)
    ADD_SUBJECT_START  = 0x20   # begin subject calibration: subject_id(1) + name(16) = 17B
    ADD_SUBJECT_SET_A  = 0x21   # record point A at slider home (no payload)
    ADD_SUBJECT_SET_B  = 0x22   # record point B at slider max (no payload)
    ADD_SUBJECT_ABORT  = 0x23   # cancel calibration in progress (no payload)
    DELETE_SUBJECT     = 0x24   # delete subject: subject_id(1)
    SET_REF            = 0x25   # set pan/tilt session reference: subject_id(1)
    SET_SLIDER_MOVE    = 0x26   # store slider move: slot(1)+start_mm(4f)+end_mm(4f)+preset(1) = 10B
    START_LOOK_AT_MOVE = 0x27   # start tracking: slider_slot(1)+subject_id(1)+max_pt_deg_s(4f) = 6B
    SWITCH_SUBJECT     = 0x28   # switch tracking target mid-move: subject_id(1)
    GET_SUBJECTS       = 0x29   # request full subject list (no payload)

    # Mount → PC
    STATUS            = 0x80
    LIMITS_FOUND      = 0x81
    ACK               = 0x82
    NACK              = 0x83
    PONG              = 0x84
    STATE_REPORT      = 0x85   # full state: 10 slots + active presets + limits
    CONFIG_REPORT     = 0x86   # config: orientation flags + 9 speed presets (73 bytes)
    HOME_COMPLETE     = 0x87   # homing finished (1 byte: axis)

    # Mount → PC  (v2)
    SUBJECT_LIST      = 0x90   # all subjects: 8 × SUBJECT_RECORD_LEN bytes (232B)
    LOOK_AT_STATUS    = 0x91   # live telemetry: slider_mm(4f)+pan_deg(4f)+tilt_deg(4f)+subj_id(1)+flags(1) = 14B
    REF_CONFIRMED     = 0x92   # reference set echo: pan_deg(4f)+tilt_deg(4f) = 8B
    CALIB_PROMPT      = 0x93   # calibration step notification: sub_state(1)

    # Hub-injected (never sent by Teensy — generated by hub ESP32 for all clients)
    LA_MOVE_DIR       = 0x94   # look-at move direction: 0=min(◀), 1=max(▶), 0xFF=stopped
    HUB_DIAG          = 0x95   # hub→USB-PC only: usb_rx_bytes(u32)+usb_rx_pkts(u32) — USB wedge diagnostic
    HUB_REINIT_ESPNOW = 0x96   # PC→hub: full esp_now reinit — recovers the hub→mount ESP-NOW send wedge
    HUB_RESTART       = 0x97   # PC→hub: full esp_restart() — escalation when 0x96 doesn't clear the wedge
    HUB_EVENT         = 0x98   # hub→USB-PC only: kind(1)+mount(1)+rssi(1)+state(1)+flags(1)+uptime_s(u32)


class Axis(IntEnum):
    PAN    = 0
    TILT   = 1
    SLIDER = 2
    ZOOM   = 3


class AxisGroup(IntEnum):
    PAN_TILT    = 0
    SLIDER_ZOOM = 1   # slider presets (4 presets)
    ZOOM        = 2   # zoom has a single independent preset


class MountState(IntEnum):
    IDLE                = 0
    JOGGING             = 1
    MOVING_TO_POS       = 2
    FINDING_LIMITS      = 3
    ERROR               = 4
    LOOK_AT_MOVE        = 5   # v2: slider moving, pan/tilt tracking subject
    CALIBRATING_SUBJECT = 6   # v2: 2-point subject calibration in progress
    LOOK_AT_PRE_AIM     = 7   # v2: pre-aiming pan/tilt before slider starts
    # NOTE: keep in sync with MountState in firmware/shared/protocol.h — a
    # value missing here makes decode_status() raise and the PC app silently
    # drop every STATUS packet the mount sends while in that state.


class CalibPrompt(IntEnum):
    """Sub-state codes sent in Cmd.CALIB_PROMPT."""
    MOVING_TO_A = 0x01   # slider moving to home — wait
    WAIT_SET_A  = 0x02   # at home: aim camera then confirm
    MOVING_TO_B = 0x03   # slider moving to max — wait
    WAIT_SET_B  = 0x04   # at max: re-aim camera then confirm
    SOLVED      = 0x05   # 3D position solved and saved
    ERROR       = 0x06   # calibration failed (bad geometry)


class MountFlag(IntEnum):
    AT_MIN_LIMIT    = 0x01
    AT_MAX_LIMIT    = 0x02
    STALL_ERROR     = 0x04
    LIMITS_SET      = 0x08   # slider/zoom limits have been found
    HAS_SLIDER      = 0x10   # mount has a physical slider axis
    REF_SET         = 0x20   # v2: pan/tilt session reference established
    LOOK_AT_ACTIVE  = 0x40   # v2: look-at move currently running
    LOOK_AT_MODE    = 0x80   # v2: slider uses 3D triangulation mode


class NackError(IntEnum):
    BAD_CRC       = 0x01
    BAD_LENGTH    = 0x02
    UNKNOWN_CMD   = 0x03
    INVALID_PARAM = 0x04
    BUSY          = 0x05
    NO_REF        = 0x06   # v2: look-at refused — session reference not set


# ---------------------------------------------------------------------------
# CRC-16/CCITT-FALSE  (poly=0x1021, init=0xFFFF, no reflect)
# ---------------------------------------------------------------------------

def crc16(data: bytes) -> int:
    crc = 0xFFFF
    for byte in data:
        crc ^= byte << 8
        for _ in range(8):
            if crc & 0x8000:
                crc = (crc << 1) ^ 0x1021
            else:
                crc <<= 1
        crc &= 0xFFFF
    return crc


# ---------------------------------------------------------------------------
# Packet building
# ---------------------------------------------------------------------------

_seq_counter = 0

def _next_seq() -> int:
    global _seq_counter
    _seq_counter = (_seq_counter + 1) & 0xFFFF
    return _seq_counter


def build_packet(mount_id: int, cmd: Cmd, payload: bytes = b"",
                 seq: Optional[int] = None) -> bytes:
    """Encode a complete packet ready for transmission."""
    if seq is None:
        seq = _next_seq()

    # LEN covers: mount_id(1) + seq(2) + cmd(1) + payload
    length = 1 + 2 + 1 + len(payload)
    header = bytes([mount_id, (seq >> 8) & 0xFF, seq & 0xFF, cmd]) + payload
    crc_input = bytes([length]) + header
    crc = crc16(crc_input)

    return bytes([PACKET_START_1, PACKET_START_2, length]) + header + bytes([crc >> 8, crc & 0xFF])


# ---------------------------------------------------------------------------
# Packet parsing
# ---------------------------------------------------------------------------

@dataclass
class Packet:
    mount_id: int
    seq: int
    cmd: Cmd
    payload: bytes


class ParseError(Exception):
    pass


def parse_packet(data: bytes) -> Packet:
    """
    Parse and validate a complete packet.
    Raises ParseError on any validation failure.
    """
    if len(data) < PACKET_MIN_SIZE:
        raise ParseError(f"Too short: {len(data)} bytes")

    if data[0] != PACKET_START_1 or data[1] != PACKET_START_2:
        raise ParseError("Bad start bytes")

    length = data[2]
    expected_total = 3 + length + 2  # start(2) + len(1) + length bytes + crc(2)

    if len(data) < expected_total:
        raise ParseError(f"Incomplete packet: need {expected_total}, have {len(data)}")

    crc_input = data[2 : 3 + length]          # from LEN byte through end of payload
    received_crc = (data[3 + length] << 8) | data[3 + length + 1]
    computed_crc = crc16(crc_input)

    if received_crc != computed_crc:
        raise ParseError(f"CRC mismatch: got {received_crc:#06x}, expected {computed_crc:#06x}")

    # Decode header fields inside the length-prefixed region
    body = data[3 : 3 + length]               # mount_id + seq(2) + cmd + payload
    if len(body) < 4:
        raise ParseError("Body too short")

    mount_id = body[0]
    seq = (body[1] << 8) | body[2]
    try:
        cmd = Cmd(body[3])
    except ValueError:
        raise ParseError(f"Unknown command: {body[3]:#04x}")

    payload = bytes(body[4:])

    return Packet(mount_id=mount_id, seq=seq, cmd=cmd, payload=payload)

# ---------------------------------------------------------------------------
# Packet stream reader  (reassembles packets from a byte stream)
# ---------------------------------------------------------------------------

class PacketReader:
    """
    Feed raw bytes from the serial port; call packets() to get complete
    parsed Packet objects.  Handles partial reads and framing.
    """

    def __init__(self):
        self._buf = bytearray()

    def feed(self, data: bytes) -> None:
        self._buf.extend(data)

    def packets(self) -> list[Packet]:
        results = []
        while True:
            # Find start sequence
            idx = self._find_start()
            if idx == -1:
                # No start found — discard everything except a possible
                # trailing 0xAA that might be the first byte of the next packet.
                if self._buf and self._buf[-1] == PACKET_START_1:
                    self._buf = bytearray([PACKET_START_1])
                else:
                    self._buf.clear()
                break
            if idx > 0:
                del self._buf[:idx]

            # Need at least 3 bytes to read LEN
            if len(self._buf) < 3:
                break

            length = self._buf[2]
            expected_total = 3 + length + 2

            if len(self._buf) < expected_total:
                break  # wait for more data

            packet_bytes = bytes(self._buf[:expected_total])
            del self._buf[:expected_total]

            try:
                results.append(parse_packet(packet_bytes))
            except ParseError as e:
                log.debug(f"Parse error (skipping packet): {e} — raw: {packet_bytes.hex(' ')}")
                # Don't re-raise — just skip this packet and keep reading.

        return results

    def _find_start(self) -> int:
        """Return index of first 0xAA 0x55 pair, or -1 if none found."""
        buf = self._buf
        for i in range(len(buf) - 1):
            if buf[i] == PACKET_START_1 and buf[i + 1] == PACKET_START_2:
                return i
        return -1


# ---------------------------------------------------------------------------
# Payload encoders  (PC → Mount)
# ---------------------------------------------------------------------------

def encode_jog(pan_vel: int, tilt_vel: int, slider_vel: int, zoom_vel: int,
               pt_preset: int = 2, sz_preset: int = 2,
               axis_mask: int = 0x0F) -> bytes:
    """
    Encode joystick-driven velocities (clamped to [-1000, 1000])
    plus speed preset indices and an optional axis mask.

    axis_mask bits: 0=pan, 1=tilt, 2=slider, 3=zoom.  0x0F = all axes (default).
    0x03 = pan+tilt only — used in CV-tracking mode so the Teensy calls
    jogPanTilt() and leaves an in-progress moveSliderTo() undisturbed.
    The extra byte is only appended when axis_mask != 0x0F so existing
    firmware that doesn't know about it is unaffected.
    """
    def clamp(v): return max(-1000, min(1000, int(v)))
    pt = max(1, min(4, pt_preset))
    sz = max(1, min(4, sz_preset))
    base = struct.pack(">hhhhBB", clamp(pan_vel), clamp(tilt_vel),
                       clamp(slider_vel), clamp(zoom_vel), pt, sz)
    if axis_mask != 0x0F:
        return base + struct.pack("B", axis_mask & 0xFF)
    return base


def encode_goto(pan: int, tilt: int, slider: int, zoom: int,
                speed_preset: int) -> bytes:
    return struct.pack(">iiiib", pan, tilt, slider, zoom, speed_preset)


def encode_move_rel(d_pan: int, d_tilt: int, d_slider: int, d_zoom: int,
                    speed_preset: int) -> bytes:
    """Relative move — Teensy adds these deltas to its current position."""
    return struct.pack(">iiiib", d_pan, d_tilt, d_slider, d_zoom, speed_preset)


def encode_save_pos(slot: int) -> bytes:
    return struct.pack(">B", slot)


def encode_set_speed_preset(axis_group: AxisGroup, preset: int,
                             max_speed: int, accel: int) -> bytes:
    return struct.pack(">BBii", int(axis_group), preset, max_speed, accel)


def encode_set_limits(axis: Axis, min_steps: int, max_steps: int) -> bytes:
    return struct.pack(">Bii", int(axis), min_steps, max_steps)


def encode_find_limits(axis: Axis, stall_threshold: int = 80) -> bytes:
    return struct.pack(">BB", int(axis), max(1, min(255, stall_threshold)))


def encode_find_home(axis: Axis, stall_threshold: int = 80) -> bytes:
    return struct.pack(">BB", int(axis), max(1, min(255, stall_threshold)))


def encode_set_orientation(pan_invert: bool, slider_invert: bool,
                           has_slider: bool = True,
                           zoom_invert: bool = False,
                           lanc_zoom: bool = False,
                           tilt_invert: bool = False,
                           look_at_mode: bool = False) -> bytes:
    flags = ((0x01 if pan_invert    else 0) |
             (0x02 if slider_invert  else 0) |
             (0x04 if has_slider     else 0) |
             (0x08 if zoom_invert    else 0) |
             (0x10 if lanc_zoom      else 0) |
             (0x20 if tilt_invert    else 0) |
             (0x40 if look_at_mode   else 0))
    return struct.pack(">B", flags)


def encode_ping(timestamp_ms: int) -> bytes:
    return struct.pack(">I", timestamp_ms & 0xFFFFFFFF)


# ---------------------------------------------------------------------------
# Payload decoders  (Mount → PC)
# ---------------------------------------------------------------------------

@dataclass
class StatusPayload:
    state: MountState
    flags: int
    # Extended fields (25-byte STATUS)
    active_pt_preset:   int = 2    # 1-4
    active_sl_preset:   int = 2    # 1-4
    slot_occupied_mask:   int = 0    # bits 0-9: slot N has stored position
    slot_at_mask:         int = 0    # bits 0-9: mount is AT slot N
    target_slot:          int = 0xFF # slot currently being moved to (0xFF = none)
    active_la_subject:    int = 0xFF # active look-at subject (0-7, 0xFF = none)

    @property
    def at_min_limit(self) -> bool:
        return bool(self.flags & MountFlag.AT_MIN_LIMIT)

    @property
    def at_max_limit(self) -> bool:
        return bool(self.flags & MountFlag.AT_MAX_LIMIT)

    @property
    def stall_error(self) -> bool:
        return bool(self.flags & MountFlag.STALL_ERROR)

    @property
    def limits_set(self) -> bool:
        return bool(self.flags & MountFlag.LIMITS_SET)

    @property
    def has_slider(self) -> bool:
        return bool(self.flags & MountFlag.HAS_SLIDER)

    @property
    def look_at_mode(self) -> bool:
        return bool(self.flags & MountFlag.LOOK_AT_MODE)


@dataclass
class StateReportPayload:
    slots: list
    slot_occupied_mask: int
    slot_at_mask: int
    active_pt_preset: int
    active_sl_preset: int
    slider_min_steps: int
    slider_max_steps: int
    zoom_min_steps: int
    zoom_max_steps: int


@dataclass
class LimitsFoundPayload:
    axis: Axis
    min_steps: int
    max_steps: int


@dataclass
class AckPayload:
    acked_seq: int


@dataclass
class NackPayload:
    nacked_seq: int
    error: NackError


def decode_status(payload: bytes) -> StatusPayload:
    if len(payload) < 9:
        raise ParseError(f"STATUS payload too short: {len(payload)} bytes")

    # ">BBBBHHB" = state, flags, pt_preset, sl_preset, occupied(16), at(16), target
    fields = struct.unpack(">BBBBHHB", payload[:9])

    # Byte [9] (added in v2): active look-at subject (0-7, 0xFF = none)
    active_la_subject = payload[9] if len(payload) >= 10 else 0xFF

    return StatusPayload(
        state              = MountState(fields[0]),
        flags              = fields[1],
        active_pt_preset   = fields[2],
        active_sl_preset   = fields[3],
        slot_occupied_mask = fields[4],
        slot_at_mask       = fields[5],
        target_slot        = fields[6],
        active_la_subject  = active_la_subject,
    )


def decode_state_report(payload: bytes) -> StateReportPayload:
    """Decode CMD_STATE_REPORT.

    Accepts two payload sizes:
      • 6 bytes  — lightweight format sent by current Teensy firmware:
                   occupied(H) | slot_at(H) | pt_preset(B) | sl_preset(B)
                   Slot position data and limits are not transmitted; the PC
                   app retains whatever values it already holds for this mount.
      • 182 bytes — full format: 10 × (pan,tilt,slider,zoom) int32 +
                   masks + presets + limits.
    """
    if len(payload) < 6:
        raise ParseError(f"STATE_REPORT payload too short: {len(payload)}")

    if len(payload) < STATE_REPORT_PAYLOAD_LEN:
        # Lightweight 6-byte format from Teensy firmware.
        occupied, at_mask = struct.unpack(">HH", payload[0:4])
        pt_preset = payload[4]
        sl_preset = payload[5]
        return StateReportPayload(
            slots=[None] * NUM_SLOTS,   # positions not transmitted
            slot_occupied_mask=occupied,
            slot_at_mask=at_mask,
            active_pt_preset=pt_preset,
            active_sl_preset=sl_preset,
            slider_min_steps=0,
            slider_max_steps=0,
            zoom_min_steps=0,
            zoom_max_steps=0,
        )

    # Full 182-byte format.
    slots = []
    for i in range(NUM_SLOTS):
        off = i * 16
        pan, tilt, slider, zoom = struct.unpack(">iiii", payload[off:off + 16])
        slots.append((pan, tilt, slider, zoom))
    occupied, at_mask = struct.unpack(">HH", payload[160:164])
    pt_preset = payload[164]
    sl_preset = payload[165]
    sl_min, sl_max, zm_min, zm_max = struct.unpack(">iiii", payload[166:182])
    return StateReportPayload(
        slots=slots,
        slot_occupied_mask=occupied,
        slot_at_mask=at_mask,
        active_pt_preset=pt_preset,
        active_sl_preset=sl_preset,
        slider_min_steps=sl_min,
        slider_max_steps=sl_max,
        zoom_min_steps=zm_min,
        zoom_max_steps=zm_max,
    )


@dataclass
class ConfigReportPayload:
    """Decoded CMD_CONFIG_REPORT (75-byte payload)."""
    pan_invert:    bool
    tilt_invert:   bool
    slider_invert: bool
    has_slider:    bool
    zoom_invert:   bool
    lanc_zoom:     bool
    # Speed presets in physical units (deg/s or mm/s, deg/s² or mm/s²)
    pt_presets: list  # list of 4 (max_speed, accel) tuples, index 0 = preset 1
    sl_presets: list  # list of 4 (max_speed, accel) tuples
    zm_preset:  tuple # (max_speed, accel)
    # StallGuard thresholds stored on the mount (bytes 73-74; 0 = unknown/old firmware)
    stall_threshold_slider: int = 0
    stall_threshold_zoom:   int = 0
    look_at_mode:           bool = False


def decode_config_report(payload: bytes) -> ConfigReportPayload:
    """
    Decode CMD_CONFIG_REPORT (75-byte payload, 73-byte accepted for old firmware).
    Layout:
      [0]       orientation flags (bit0=pan_inv, bit1=slider_inv, bit2=has_slider, bit3=zoom_inv, bit4=lanc_zoom, bit5=tilt_inv)
      [1..32]   4 × PT preset: uint32 max_speed + uint32 accel (presets 1-4)
      [33..64]  4 × SL preset: uint32 max_speed + uint32 accel
      [65..72]  1 × ZM preset: uint32 max_speed + uint32 accel
      [73]      stall_threshold[AXIS_SLIDER]
      [74]      stall_threshold[AXIS_ZOOM]
    """
    if len(payload) < 73:
        raise ParseError(f"CONFIG_REPORT payload too short: {len(payload)}")
    ori = payload[0]
    pan_invert    = bool(ori & 0x01)
    slider_invert = bool(ori & 0x02)
    has_slider    = bool(ori & 0x04)
    zoom_invert   = bool(ori & 0x08)
    lanc_zoom     = bool(ori & 0x10)
    tilt_invert   = bool(ori & 0x20)
    look_at_mode  = bool(ori & 0x40)
    pt_presets = []
    for p in range(4):
        off = 1 + p * 8
        spd, acc = struct.unpack(">II", payload[off:off + 8])
        pt_presets.append((spd, acc))
    sl_presets = []
    for p in range(4):
        off = 33 + p * 8
        spd, acc = struct.unpack(">II", payload[off:off + 8])
        sl_presets.append((spd, acc))
    zm_spd, zm_acc = struct.unpack(">II", payload[65:73])
    sg_slider = payload[73] if len(payload) >= 75 else 0
    sg_zoom   = payload[74] if len(payload) >= 75 else 0
    return ConfigReportPayload(
        pan_invert=pan_invert,
        tilt_invert=tilt_invert,
        slider_invert=slider_invert,
        has_slider=has_slider,
        zoom_invert=zoom_invert,
        lanc_zoom=lanc_zoom,
        look_at_mode=look_at_mode,
        pt_presets=pt_presets,
        sl_presets=sl_presets,
        zm_preset=(zm_spd, zm_acc),
        stall_threshold_slider=sg_slider,
        stall_threshold_zoom=sg_zoom,
    )


def decode_limits_found(payload: bytes) -> LimitsFoundPayload:
    axis_raw, min_steps, max_steps = struct.unpack(">Bii", payload[:9])
    return LimitsFoundPayload(axis=Axis(axis_raw), min_steps=min_steps, max_steps=max_steps)


def decode_home_complete(payload: bytes) -> Axis:
    """Decode CMD_HOME_COMPLETE — returns the axis that finished homing."""
    return Axis(payload[0])


def decode_ack(payload: bytes) -> AckPayload:
    seq, = struct.unpack(">H", payload[:2])
    return AckPayload(acked_seq=seq)


def decode_nack(payload: bytes) -> NackPayload:
    seq, error_raw = struct.unpack(">HB", payload[:3])
    return NackPayload(nacked_seq=seq, error=NackError(error_raw))


def decode_pong(payload: bytes) -> int:
    ts, = struct.unpack(">I", payload[:4])
    return ts


# ---------------------------------------------------------------------------
# Convenience packet constructors
# ---------------------------------------------------------------------------

def pkt_jog(mount_id: int, pan_vel: int, tilt_vel: int,
            slider_vel: int, zoom_vel: int,
            pt_preset: int = 2, sz_preset: int = 2,
            axis_mask: int = 0x0F) -> bytes:
    """Sends a relative velocity command (joystick movement)."""
    return build_packet(mount_id, Cmd.JOG,
                        encode_jog(pan_vel, tilt_vel, slider_vel, zoom_vel,
                                   pt_preset, sz_preset, axis_mask))

def pkt_goto(mount_id: int, pan: int, tilt: int, slider: int, zoom: int,
             speed_preset: int) -> bytes:
    return build_packet(mount_id, Cmd.GOTO,
                        encode_goto(pan, tilt, slider, zoom, speed_preset))


def pkt_move_rel(mount_id: int, d_pan: int, d_tilt: int, d_slider: int, d_zoom: int,
                 speed_preset: int = 2) -> bytes:
    return build_packet(mount_id, Cmd.MOVE_REL,
                        encode_move_rel(d_pan, d_tilt, d_slider, d_zoom, speed_preset))

def pkt_save_pos(mount_id: int, slot: int) -> bytes:
    return build_packet(mount_id, Cmd.SAVE_POS, encode_save_pos(slot))

def pkt_set_speed_preset(mount_id: int, axis_group: AxisGroup, preset: int,
                          max_speed: int, accel: int) -> bytes:
    return build_packet(mount_id, Cmd.SET_SPEED_PRESET,
                        encode_set_speed_preset(axis_group, preset, max_speed, accel))

def pkt_set_limits(mount_id: int, axis: Axis, min_steps: int, max_steps: int) -> bytes:
    return build_packet(mount_id, Cmd.SET_LIMITS, encode_set_limits(axis, min_steps, max_steps))

def pkt_find_limits(mount_id: int, axis: Axis, stall_threshold: int = 80) -> bytes:
    return build_packet(mount_id, Cmd.FIND_LIMITS, encode_find_limits(axis, stall_threshold))

def pkt_find_home(mount_id: int, axis: Axis, stall_threshold: int = 80) -> bytes:
    return build_packet(mount_id, Cmd.FIND_HOME, encode_find_home(axis, stall_threshold))

def pkt_set_stall_threshold(mount_id: int, axis: Axis, threshold: int) -> bytes:
    return build_packet(mount_id, Cmd.SET_STALL_THRESHOLD,
                        struct.pack(">BB", int(axis), max(1, min(255, threshold))))

def pkt_set_orientation(mount_id: int, pan_invert: bool, slider_invert: bool,
                        has_slider: bool = True,
                        zoom_invert: bool = False,
                        lanc_zoom: bool = False,
                        tilt_invert: bool = False,
                        look_at_mode: bool = False) -> bytes:
    return build_packet(mount_id, Cmd.SET_ORIENTATION,
                        encode_set_orientation(pan_invert, slider_invert,
                                               has_slider, zoom_invert, lanc_zoom,
                                               tilt_invert, look_at_mode))

def pkt_e_stop(mount_id: int = MOUNT_BROADCAST) -> bytes:
    return build_packet(mount_id, Cmd.E_STOP)

def pkt_get_status(mount_id: int) -> bytes:
    return build_packet(mount_id, Cmd.GET_STATUS)

def pkt_ping(mount_id: int = MOUNT_BROADCAST) -> bytes:
    import time
    return build_packet(mount_id, Cmd.PING, encode_ping(int(time.monotonic() * 1000)))


def encode_store_pos(slot: int) -> bytes:
    return struct.pack(">B", slot & 0xFF)


def encode_clear_pos(slot: int) -> bytes:
    return struct.pack(">B", slot & 0xFF)


def encode_set_active_preset(axis_group: AxisGroup, preset: int) -> bytes:
    return struct.pack(">BB", int(axis_group), max(1, min(4, preset)))


def encode_save_speeds(pt_presets: list[tuple[int, int]],
                       sl_presets: list[tuple[int, int]],
                       zm_preset:  tuple[int, int]) -> bytes:
    """
    Build 72-byte CMD_SAVE_SPEEDS payload.

    pt_presets: list of 4 (max_speed, accel) tuples for presets 1-4
    sl_presets: list of 4 (max_speed, accel) tuples for presets 1-4
    zm_preset:  single (max_speed, accel) tuple
    """
    out = b""
    for spd, acc in pt_presets[:4]:
        out += struct.pack(">II", spd, acc)
    for spd, acc in sl_presets[:4]:
        out += struct.pack(">II", spd, acc)
    spd, acc = zm_preset
    out += struct.pack(">II", spd, acc)
    return out


def encode_goto_slot(slot: int, pt_preset: int = 2, sl_preset: int = 2,
                     axis_mask: int = 0x0F) -> bytes:
    """axis_mask 0x0F = all axes (default).  0x04 = slider only (CV-tracking mode).
    pt_preset and sl_preset are sent separately so each axis group respects its
    own active speed — e.g. slider on speed 2 won't be driven at pan/tilt speed 4."""
    base = struct.pack(">BBB", slot & 0xFF,
                       max(1, min(4, pt_preset)),
                       max(1, min(4, sl_preset)))
    if axis_mask != 0x0F:
        return base + struct.pack("B", axis_mask & 0xFF)
    return base


def pkt_goto_slot(mount_id: int, slot: int, pt_preset: int = 2, sl_preset: int = 2,
                  axis_mask: int = 0x0F) -> bytes:
    return build_packet(mount_id, Cmd.GOTO_SLOT,
                        encode_goto_slot(slot, pt_preset, sl_preset, axis_mask))


def pkt_get_state(mount_id: int) -> bytes:
    return build_packet(mount_id, Cmd.GET_STATE)

def pkt_store_pos(mount_id: int, slot: int) -> bytes:
    return build_packet(mount_id, Cmd.STORE_POS, encode_store_pos(slot))

def pkt_clear_pos(mount_id: int, slot: int) -> bytes:
    return build_packet(mount_id, Cmd.CLEAR_POS, encode_clear_pos(slot))

def pkt_set_active_preset(mount_id: int, axis_group: AxisGroup, preset: int) -> bytes:
    return build_packet(mount_id, Cmd.SET_ACTIVE_PRESET,
                        encode_set_active_preset(axis_group, preset))

def pkt_get_config(mount_id: int) -> bytes:
    """Request configuration (speed presets + orientation) from a mount."""
    return build_packet(mount_id, Cmd.GET_CONFIG)


def pkt_save_speeds(mount_id: int,
                    pt_presets: list[tuple[int, int]],
                    sl_presets: list[tuple[int, int]],
                    zm_preset:  tuple[int, int]) -> bytes:
    return build_packet(mount_id, Cmd.SAVE_SPEEDS,
                        encode_save_speeds(pt_presets, sl_presets, zm_preset))


# ---------------------------------------------------------------------------
# v2 — Payload dataclasses  (decoded Mount → PC packets)
# ---------------------------------------------------------------------------

@dataclass
class SubjectRecord:
    """One entry from CMD_SUBJECT_LIST."""
    subject_id:  int          # 0–7 (position in array)
    valid:       bool
    name:        str          # up to 16 chars
    x_mm:        float = 0.0
    y_mm:        float = 0.0
    z_mm:        float = 0.0


@dataclass
class LookAtStatusPayload:
    """Decoded CMD_LOOK_AT_STATUS (14-byte payload)."""
    slider_pos_mm: float
    pan_deg:       float
    tilt_deg:      float
    subject_id:    int
    flags:         int   # bitmask — FLAG_REF_SET, FLAG_LOOK_AT_ACTIVE

    @property
    def ref_set(self) -> bool:
        return bool(self.flags & MountFlag.REF_SET)

    @property
    def look_at_active(self) -> bool:
        return bool(self.flags & MountFlag.LOOK_AT_ACTIVE)


@dataclass
class RefConfirmedPayload:
    """Decoded CMD_REF_CONFIRMED (8-byte payload)."""
    pan_deg:  float
    tilt_deg: float


# ---------------------------------------------------------------------------
# v2 — Encoders  (PC → Mount)
# ---------------------------------------------------------------------------

def encode_add_subject_start(subject_id: int, name: str) -> bytes:
    """17 bytes: subject_id(1) + name(16, null-padded)."""
    name_bytes = name.encode("utf-8")[:SUBJECT_NAME_LEN]
    name_bytes = name_bytes.ljust(SUBJECT_NAME_LEN, b"\x00")
    return struct.pack(">B", subject_id & 0x07) + name_bytes


def encode_delete_subject(subject_id: int) -> bytes:
    return struct.pack(">B", subject_id & 0x07)


def encode_set_ref(subject_id: int) -> bytes:
    # 0xFF = manual ref (sentinel) — must not be masked to 0x07
    val = 0xFF if subject_id == 0xFF else (subject_id & 0x07)
    return struct.pack(">B", val)


def encode_set_slider_move(slot: int, start_mm: float, end_mm: float,
                           speed_preset: int) -> bytes:
    """10 bytes: slot(1) + start_mm(4f BE) + end_mm(4f BE) + preset(1)."""
    return struct.pack(">BffB",
                       slot & 0x07,
                       start_mm,
                       end_mm,
                       max(1, min(4, speed_preset)))


def encode_switch_subject(subject_id: int) -> bytes:
    return struct.pack(">B", subject_id & 0x07)


# ---------------------------------------------------------------------------
# v2 — Decoders  (Mount → PC)
# ---------------------------------------------------------------------------

def decode_subject_list(payload: bytes) -> list[SubjectRecord]:
    """
    Decode CMD_SUBJECT_LIST (232-byte payload).
    Returns a list of MAX_SUBJECTS SubjectRecord objects.
    """
    if len(payload) < SUBJECT_LIST_PAYLOAD_LEN:
        raise ParseError(f"SUBJECT_LIST payload too short: {len(payload)} bytes, need {SUBJECT_LIST_PAYLOAD_LEN}")
    records = []
    for i in range(MAX_SUBJECTS):
        off = i * SUBJECT_RECORD_LEN
        valid = bool(payload[off])
        name_bytes = payload[off + 1: off + 1 + SUBJECT_NAME_LEN]
        name = name_bytes.rstrip(b"\x00").decode("utf-8", errors="replace")
        x_mm, y_mm, z_mm = struct.unpack(">fff", payload[off + 17: off + 29])
        records.append(SubjectRecord(
            subject_id=i,
            valid=valid,
            name=name,
            x_mm=x_mm,
            y_mm=y_mm,
            z_mm=z_mm,
        ))
    return records


def decode_look_at_status(payload: bytes) -> LookAtStatusPayload:
    """Decode CMD_LOOK_AT_STATUS (14-byte payload)."""
    if len(payload) < 14:
        raise ParseError(f"LOOK_AT_STATUS payload too short: {len(payload)}")
    slider_mm, pan_deg, tilt_deg = struct.unpack(">fff", payload[0:12])
    subject_id = payload[12]
    flags = payload[13]
    return LookAtStatusPayload(
        slider_pos_mm=slider_mm,
        pan_deg=pan_deg,
        tilt_deg=tilt_deg,
        subject_id=subject_id,
        flags=flags,
    )


def decode_ref_confirmed(payload: bytes) -> RefConfirmedPayload:
    """Decode CMD_REF_CONFIRMED (8-byte payload)."""
    if len(payload) < 8:
        raise ParseError(f"REF_CONFIRMED payload too short: {len(payload)}")
    pan_deg, tilt_deg = struct.unpack(">ff", payload[0:8])
    return RefConfirmedPayload(pan_deg=pan_deg, tilt_deg=tilt_deg)


def decode_calib_prompt(payload: bytes) -> CalibPrompt:
    """Decode CMD_CALIB_PROMPT (1-byte payload)."""
    if len(payload) < 1:
        raise ParseError("CALIB_PROMPT payload empty")
    return CalibPrompt(payload[0])


# ---------------------------------------------------------------------------
# v2 — Convenience packet constructors
# ---------------------------------------------------------------------------

def pkt_add_subject_start(mount_id: int, subject_id: int, name: str) -> bytes:
    """Begin 2-point subject calibration for slot subject_id."""
    return build_packet(mount_id, Cmd.ADD_SUBJECT_START,
                        encode_add_subject_start(subject_id, name))


def pkt_add_subject_set_a(mount_id: int) -> bytes:
    """Record observation A (slider at home, pan/tilt at current position)."""
    return build_packet(mount_id, Cmd.ADD_SUBJECT_SET_A)


def pkt_add_subject_set_b(mount_id: int) -> bytes:
    """Record observation B (slider at max, pan/tilt at current position)."""
    return build_packet(mount_id, Cmd.ADD_SUBJECT_SET_B)


def pkt_add_subject_abort(mount_id: int) -> bytes:
    """Abort an in-progress subject calibration."""
    return build_packet(mount_id, Cmd.ADD_SUBJECT_ABORT)


def pkt_delete_subject(mount_id: int, subject_id: int) -> bytes:
    return build_packet(mount_id, Cmd.DELETE_SUBJECT,
                        encode_delete_subject(subject_id))


def pkt_set_ref(mount_id: int, subject_id: int) -> bytes:
    """Set pan/tilt session reference by aiming at a known subject."""
    return build_packet(mount_id, Cmd.SET_REF, encode_set_ref(subject_id))


def pkt_set_slider_move(mount_id: int, slot: int, start_mm: float,
                         end_mm: float, speed_preset: int) -> bytes:
    return build_packet(mount_id, Cmd.SET_SLIDER_MOVE,
                        encode_set_slider_move(slot, start_mm, end_mm, speed_preset))


def pkt_start_look_at_move(mount_id: int, subject_id: int,
                            direction: int, speed_preset: int = 2) -> bytes:
    """3 bytes: subject_id(1) + direction(1) + speed_preset(1).
    direction: 0 = go to min/left limit, 1 = go to max/right limit.
    speed_preset: 1–4."""
    payload = bytes([subject_id & 0x07, direction & 0x01, max(1, min(4, speed_preset))])
    return build_packet(mount_id, Cmd.START_LOOK_AT_MOVE, payload)


def pkt_switch_subject(mount_id: int, subject_id: int) -> bytes:
    """Switch tracking target while a look-at move is running."""
    return build_packet(mount_id, Cmd.SWITCH_SUBJECT,
                        encode_switch_subject(subject_id))


def pkt_get_subjects(mount_id: int) -> bytes:
    """Request the full subject list from the mount."""
    return build_packet(mount_id, Cmd.GET_SUBJECTS)
